name: Hourly Feature Generation

on:
  schedule:
    - cron: '0 * * * *' # runs the job at the start of every hour.

jobs:
  run_feature_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run feature script
        run: python feature_script.py 
