# .github/workflows/mlops_pipeline.yml
name: AQI MLOps Pipeline

# This workflow will now run on pushes to your 'master' branch
on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 * * * *" # Run feature ingestion every hour
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  ingest_features:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyarrow
      - name: Install dependencies for feature ingestion
        run: |
          python -m pip install --upgrade pip
          pip install hopsworks==4.2.* pandas pyarrow

      - name: Run feature ingestion script (e.g., feature_script.py)
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}        
        run: |
          python feature_script.py

  train_and_register_model:
    runs-on: ubuntu-latest
    needs: ingest_features

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies for training
        run: |
          python -m pip install --upgrade pip
          pip install hopsworks>=3.6.0 scikit-learn pandas joblib

      - name: Run training and registration script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}  
        run: |
          python training_script.py
