name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *' #runs the job at midnight every day (00:00)

jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        run: python training_script.py 
